import Head from 'next/head'
import TodoList from '../components/TodoList/TodoList'
import styles from '../styles/Home.module.css'
import { Provider } from 'react-redux'
import { configureStore } from '../store'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={configureStore()}>
          
      </Provider>

      <TodoList/>


    </div>
  )
}
